package com.aioh;

public enum AiohDatabaseEditorState {
    DATABASES_DISPLAY,
    NEW_DATABASE,
    DELETE_DATABASE,
    TABLES_DISPLAY,
    NEW_TABLE_NAME,
    NEW_TABLE_COLUMNS,
    DELETE_TABLE,
    COLUMNS_DISPLAY,
    COLUMN_RENAME,
    CELL_UPDATE,
}
