package com.aioh;

public enum AiohDatabaseEditorState {
    DATABASES_DISPLAY,
    NEW_DATABASE,
    DELETE_DATABASE,
    TABLES_DISPLAY,
    NEW_TABLE_NAME,
    NEW_TABLE_COLUMNS,
    NEW_TABLE_COLUMN_NAME,
    NEW_TABLE_COLUMN_TYPE,
    NEW_TABLE_VARCHAR_SIZE,
    DELETE_TABLE,
    COLUMNS_DISPLAY,
    COLUMN_RENAME,
    CELL_UPDATE,
}
